# Generated by Django 5.2.9 on 2026-01-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Textbook',
                'verbose_name_plural': 'Textbooks',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='vocab_maste_title_3f0864_idx')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='vocab_master.textbook')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['textbook', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='vocab_master.unit')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], db_index=True, max_length=20)),
                ('definition', models.TextField()),
                ('urdu_meaning', models.TextField()),
                ('phonetic_spelling', models.CharField(blank=True, db_index=True, max_length=100)),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='pronunciations/')),
                ('reviewed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='vocab_master.lesson')),
            ],
            options={
                'verbose_name': 'Vocabulary',
                'verbose_name_plural': 'Vocabulary',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='vocab_master.vocabulary')),
            ],
            options={
                'verbose_name': 'Synonym',
                'verbose_name_plural': 'Synonyms',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(db_index=True)),
                ('sentence_type', models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound'), ('complex', 'Complex')], db_index=True, max_length=20)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocab_master.vocabulary')),
            ],
            options={
                'verbose_name': 'Example sentence',
                'verbose_name_plural': 'Example sentences',
                'ordering': ['sentence_type', 'sentence'],
            },
        ),
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonyms', to='vocab_master.vocabulary')),
            ],
            options={
                'verbose_name': 'Antonym',
                'verbose_name_plural': 'Antonyms',
                'ordering': ['word'],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['title'], name='vocab_maste_title_34cb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['order'], name='vocab_maste_order_7861c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('textbook', 'title'), name='unique_unit_per_textbook'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['title'], name='vocab_maste_title_ca3116_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order'], name='vocab_maste_order_c2388e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'title'), name='unique_lesson_per_unit'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['word'], name='vocab_maste_word_7aa9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['part_of_speech'], name='vocab_maste_part_of_8553ba_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['reviewed'], name='vocab_maste_reviewe_17202b_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_at'], name='vocab_maste_created_a6bb60_idx'),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=models.Index(fields=['word'], name='vocab_maste_word_f927eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='synonym',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'word'), name='unique_synonym_per_vocab'),
        ),
        migrations.AddIndex(
            model_name='examplesentence',
            index=models.Index(fields=['sentence_type'], name='vocab_maste_sentenc_87d2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='examplesentence',
            index=models.Index(fields=['sentence'], name='vocab_maste_sentenc_e4be5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='examplesentence',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'sentence'), name='unique_example_per_vocab'),
        ),
        migrations.AddIndex(
            model_name='antonym',
            index=models.Index(fields=['word'], name='vocab_maste_word_d7884f_idx'),
        ),
        migrations.AddConstraint(
            model_name='antonym',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'word'), name='unique_antonym_per_vocab'),
        ),
    ]
