# Generated by Django 5.1.4 on 2025-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_master', '0002_alter_vocabulary_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antonym',
            options={'verbose_name': 'Antonym', 'verbose_name_plural': 'Antonyms'},
        ),
        migrations.AlterModelOptions(
            name='examplesentence',
            options={'verbose_name': 'Example sentence', 'verbose_name_plural': 'Example sentences'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'verbose_name': 'Textbook', 'verbose_name_plural': 'Textbooks'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name': 'Vocabulary', 'verbose_name_plural': 'Vocabulary'},
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
