# Generated by Django 5.1.4 on 2025-12-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_master', '0003_alter_antonym_options_alter_examplesentence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antonym',
            options={'ordering': ['word'], 'verbose_name': 'Antonym', 'verbose_name_plural': 'Antonyms'},
        ),
        migrations.AlterModelOptions(
            name='examplesentence',
            options={'ordering': ['sentence_type', 'sentence'], 'verbose_name': 'Example sentence', 'verbose_name_plural': 'Example sentences'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['unit', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'ordering': ['word'], 'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'ordering': ['title'], 'verbose_name': 'Textbook', 'verbose_name_plural': 'Textbooks'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['textbook', 'order'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['word'], 'verbose_name': 'Vocabulary', 'verbose_name_plural': 'Vocabulary'},
        ),
    ]
