# Generated by Django 5.1.4 on 2025-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_master', '0004_alter_antonym_options_alter_examplesentence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examplesentence',
            name='sentence',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='examplesentence',
            name='sentence_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound'), ('complex', 'Complex')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='phonetic_spelling',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='antonym',
            index=models.Index(fields=['word'], name='vocab_maste_word_d7884f_idx'),
        ),
        migrations.AddIndex(
            model_name='examplesentence',
            index=models.Index(fields=['sentence_type'], name='vocab_maste_sentenc_87d2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='examplesentence',
            index=models.Index(fields=['sentence'], name='vocab_maste_sentenc_e4be5c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['title'], name='vocab_maste_title_ca3116_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order'], name='vocab_maste_order_c2388e_idx'),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=models.Index(fields=['word'], name='vocab_maste_word_f927eb_idx'),
        ),
        migrations.AddIndex(
            model_name='textbook',
            index=models.Index(fields=['title'], name='vocab_maste_title_3f0864_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['title'], name='vocab_maste_title_34cb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['order'], name='vocab_maste_order_7861c6_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['word'], name='vocab_maste_word_7aa9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['part_of_speech'], name='vocab_maste_part_of_8553ba_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['reviewed'], name='vocab_maste_reviewe_17202b_idx'),
        ),
    ]
