# Generated by Django 5.1.4 on 2025-12-05 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_master', '0005_alter_antonym_word_alter_examplesentence_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='antonym',
            unique_together={('vocabulary', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='examplesentence',
            unique_together={('vocabulary', 'sentence')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together={('vocabulary', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('textbook', 'title')},
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_at'], name='vocab_maste_created_a6bb60_idx'),
        ),
    ]
