# Generated by Django 5.1.4 on 2025-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_master', '0006_vocabulary_created_at_vocabulary_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='antonym',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examplesentence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='antonym',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'word'), name='unique_antonym_per_vocab'),
        ),
        migrations.AddConstraint(
            model_name='examplesentence',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'sentence'), name='unique_example_per_vocab'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'title'), name='unique_lesson_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='synonym',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'word'), name='unique_synonym_per_vocab'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('textbook', 'title'), name='unique_unit_per_textbook'),
        ),
    ]
