# Generated by Django 5.2.9 on 2025-12-27 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_pronunciationattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='pronunciationattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='readinglesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='readinglesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['lesson', 'created_at'], name='reading_pro_lesson__865b81_idx'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['user', 'created_at'], name='reading_pro_user_id_e99be6_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglesson',
            index=models.Index(fields=['unit', 'order'], name='reading_rea_unit_id_1f95d3_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglesson',
            index=models.Index(fields=['created_at'], name='reading_rea_created_80672c_idx'),
        ),
    ]
