# Generated by Django 5.1.4 on 2025-12-07 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTextbook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TranslationUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='translation.translationtextbook')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('textbook', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='TranslationLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('english_chunk', models.TextField(blank=True)),
                ('urdu_chunk', models.TextField(blank=True)),
                ('source_language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(default='ur', max_length=10)),
                ('normalized_english', models.TextField(blank=True)),
                ('normalized_urdu', models.TextField(blank=True)),
                ('audio_cache_url', models.URLField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='translation.translationunit')),
            ],
            options={
                'ordering': ['lesson_number'],
                'unique_together': {('unit', 'lesson_number')},
            },
        ),
    ]
