# Generated by Django 5.2.9 on 2026-02-19 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_vocabularytestanswer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_vocabularytestattempt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'content_vocabularytestquestion',
                'ordering': ['order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'content_vocabularytestsession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChunkComprehensionFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('level', models.CharField(choices=[('literal', 'Literal'), ('inferential', 'Inferential'), ('evaluative', 'Evaluative')], default='literal', max_length=20)),
                ('depth_level', models.PositiveSmallIntegerField(default=3, help_text='Difficulty level within this Bloom stage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(help_text='Order of focus within the chunk (Literal → Inferential → Evaluative)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('english_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lesson_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False)),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_data', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.chunkcomprehensionfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.TextField(blank=True, help_text='For MCQ: One option per line', null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('open_ended', 'Open Ended')], default='mcq', max_length=30)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkcomprehensionfocus')),
            ],
            options={
                'ordering': ['focus_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mastered', models.BooleanField(default=False, help_text='Automatically True when score_percent == 100.')),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('questions_data', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkcomprehensionfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprehension Test Attempt',
                'verbose_name_plural': 'Comprehension Test Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('attempt_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('selected_answer', models.CharField(blank=True, max_length=255)),
                ('open_ended_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('practice_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.comprehensionpracticeattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.comprehensionquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_question_attempts', to=settings.AUTH_USER_MODEL)),
                ('test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.comprehensiontestattempt')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(help_text='e.g. Parts of Speech, Tense, Clause, Sentence Structure', max_length=100)),
                ('order_index', models.PositiveIntegerField(help_text='Controls global progression order across the curriculum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'name'],
                'indexes': [models.Index(fields=['slug'], name='content_gra_slug_4bcbfb_idx'), models.Index(fields=['category'], name='content_gra_categor_fd4d73_idx'), models.Index(fields=['order_index'], name='content_gra_order_i_703431_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkGrammarFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('depth_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_instances', to='content.grammarconcept')),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False)),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_data', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.chunkgrammarfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.TextField(blank=True, help_text='For MCQ: One option per line', null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('rewrite', 'Rewrite Sentence'), ('identify', 'Identify Part / Function')], default='mcq', max_length=30)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkgrammarfocus')),
            ],
            options={
                'ordering': ['focus_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='content.grammarconcept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.grammarrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mastered', models.BooleanField(default=False, help_text='Automatically True when score_percent == 100.')),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_snapshot', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkgrammarfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('practice_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.grammarpracticeattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.grammarquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_question_attempts', to=settings.AUTH_USER_MODEL)),
                ('test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.grammartestattempt')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display order within the lesson')),
                ('english_text', models.TextField()),
                ('translated_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chunk_audio/')),
                ('translated_audio_file', models.FileField(blank=True, null=True, upload_to='chunk_audio_urdu/')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated time to complete this chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChunkWritingFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('depth_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_focuses', to='content.lessonchunk')),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='chunkgrammarfocus',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_focuses', to='content.lessonchunk'),
        ),
        migrations.AddField(
            model_name='chunkcomprehensionfocus',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_focuses', to='content.lessonchunk'),
        ),
        migrations.CreateModel(
            name='PronunciationFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('sequence_order', models.PositiveSmallIntegerField(help_text='Order of focus within the chunk (1, 2, or 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_focuses', to='content.lessonchunk')),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('recording', models.FileField(blank=True, null=True, upload_to='student_audio/')),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempt_type', models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], default='practice', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to='content.lessonchunk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to=settings.AUTH_USER_MODEL)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.pronunciationfocus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('best_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='content.pronunciationfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_mastery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(help_text='Global learning sequence. Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1. Global Punctuation Mark',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['order_index'], name='content_pun_order_i_5ec06a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkPunctuationFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(help_text='e.g., Using Commas in a List', max_length=200)),
                ('focus_description', models.TextField()),
                ('depth_level', models.PositiveSmallIntegerField(default=1, help_text='Difficulty Level (1: Beginner, 5: Advanced)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(default=1, help_text='Order within the chunk (1, 2, or 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_focuses', to='content.lessonchunk')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.punctuationmark')),
            ],
            options={
                'verbose_name': '3. Chunk Punctuation Focus',
                'verbose_name_plural': '3. Chunk Punctuation Focuses',
                'ordering': ['chunk', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False)),
                ('questions_data', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.chunkpunctuationfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.TextField(blank=True, help_text="For MCQ: Separate options with '|'. Example: Option A | Option B")),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('insert', 'Insert Mark'), ('fix', 'Correct Sentence')], default='mcq', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('explanation', models.TextField(blank=True, help_text='Shown to help the student learn from mistakes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkpunctuationfocus')),
            ],
            options={
                'verbose_name': '5. Punctuation Question',
                'ordering': ['focus', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='content.punctuationmark')),
            ],
            options={
                'verbose_name': '2. Global Punctuation Rule',
            },
        ),
        migrations.CreateModel(
            name='PunctuationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.punctuationrule')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkPunctuationFocusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_rules', to='content.chunkpunctuationfocus')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.punctuationrule')),
            ],
            options={
                'verbose_name': '4. Focus-Rule Mapping',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mastered', models.BooleanField(default=False, help_text='Automatically True when score_percent == 100.')),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('questions_data', models.JSONField(default=dict, help_text='Stores questions and answers for this attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkpunctuationfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punctuation Test Attempt',
                'verbose_name_plural': 'Punctuation Test Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_level', models.CharField(help_text='Example: 9th, 10th, Inter, BA', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_level', 'title'],
                'indexes': [models.Index(fields=['class_level'], name='content_tex_class_l_446d9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.textbook')),
            ],
            options={
                'ordering': ['textbook', 'number'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.unit'),
        ),
        migrations.CreateModel(
            name='UnitTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('punctuation', 'Punctuation'), ('comprehension', 'Comprehension'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation')], db_index=True, max_length=20)),
                ('bloom_level', models.CharField(blank=True, choices=[('literal', 'Literal'), ('inferential', 'Inferential'), ('evaluative', 'Evaluative')], help_text="If comprehension question, which Bloom's level?", max_length=20, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('matching', 'Matching')], default='mcq', max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text="For MCQ: ['Option A', 'Option B', 'Option C', 'Option D']")),
                ('correct_answer', models.TextField(help_text='The correct answer for grading')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveIntegerField(help_text='Question order within the test')),
                ('points', models.PositiveSmallIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('grammar_concept', models.ForeignKey(blank=True, help_text='If grammar question, which concept?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.grammarconcept')),
                ('punctuation_mark', models.ForeignKey(blank=True, help_text='If punctuation question, which mark?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.punctuationmark')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UnitTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(help_text='The answer provided by the student')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.unittestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('passed', models.BooleanField(default=False)),
                ('domain_scores', models.JSONField(default=dict, help_text="Breakdown by domain: {'vocabulary': 80, 'grammar': 70, ...}")),
                ('test_data', models.JSONField(default=dict, help_text='Complete test structure with questions and correct answers')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='content.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='unittestquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.unittestsession'),
        ),
        migrations.CreateModel(
            name='UnitWritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('stage', models.CharField(choices=[('paragraph', 'Paragraph'), ('essay', 'Essay'), ('academic_genre', 'Academic/Professional Genre')], max_length=50)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='content.unit')),
            ],
            options={
                'ordering': ['unit_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('urdu', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('antonyms', models.TextField(blank=True, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default='noun', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(blank=True, help_text='Optional: link vocabulary to a specific chunk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to='content.lessonchunk')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to='content.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'word'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Groups attempts from same practice session', max_length=100)),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Retry cycle (1, 2, 3, ...)')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_attempts', to=settings.AUTH_USER_MODEL)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.vocabularyitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='unittestquestion',
            name='vocabulary_item',
            field=models.ForeignKey(blank=True, help_text='If vocabulary question, which item?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.vocabularyitem'),
        ),
        migrations.CreateModel(
            name='StudentVocabMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Needs Review'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_mastery_records', to=settings.AUTH_USER_MODEL)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='content.vocabularyitem')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyUnitTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('questions_data', models.JSONField(default=dict, help_text='Snapshot of vocabulary questions and answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lessonchunk')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
                ('unit_test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_attempts', to='content.unittestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_unit_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('sentence', 'Sentence'), ('paragraph', 'Paragraph'), ('essay', 'Essay')], default='sentence', max_length=20)),
                ('prompt_text', models.TextField()),
                ('expected_keywords', models.TextField(blank=True, help_text='Comma-separated keywords expected in student responses')),
                ('rubric', models.JSONField(blank=True, default=dict, help_text="Rubric criteria stored as JSON: {'criterion': {'max_score': 5, 'description': '...'}}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='content.chunkwritingfocus')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='content.unitwritingtask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WritingPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('response_text', models.TextField()),
                ('keyword_match_score', models.PositiveSmallIntegerField(blank=True, help_text='Automated score based on keyword matching', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passed', models.BooleanField(default=False, help_text='True if score meets passing threshold (typically 100% for practice)')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.chunkwritingfocus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_practice_attempts', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.writingprompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cycle_number', models.PositiveSmallIntegerField(default=1, help_text='Increments when restarting after 3 failures', validators=[django.core.validators.MinValueValidator(1)])),
                ('response_text', models.TextField()),
                ('rubric_scores', models.JSONField(default=dict, help_text='Stores rubric evaluation scores per criterion')),
                ('overall_score', models.PositiveSmallIntegerField(help_text='Aggregate score percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mastered', models.BooleanField(default=False, help_text='True if overall_score == 100 (for chunk-level) or >=70 (for unit-level)')),
                ('feedback', models.TextField(blank=True, help_text='Teacher or AI feedback')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkwritingfocus')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.writingprompt')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.unitwritingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comprehensionpracticeattempt',
            index=models.Index(fields=['user', 'focus'], name='content_com_user_id_0c2bca_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionpracticeattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_com_user_id_7cd89b_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionpracticeattempt',
            index=models.Index(fields=['is_passed'], name='content_com_is_pass_ad33c3_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionpracticeattempt',
            index=models.Index(fields=['attempted_at'], name='content_com_attempt_b65749_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionpracticeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_comprehension_practice_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['focus'], name='content_com_focus_i_95b6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['question_type'], name='content_com_questio_84f823_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['difficulty'], name='content_com_difficu_d4ac75_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensiontestattempt',
            index=models.Index(fields=['user', 'focus'], name='content_com_user_id_7a4cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensiontestattempt',
            index=models.Index(fields=['user', 'focus', 'is_mastered'], name='content_com_user_id_1555dd_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensiontestattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_com_user_id_c570cd_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensiontestattempt',
            index=models.Index(fields=['created_at'], name='content_com_created_93ffca_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprehensiontestattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_comprehension_test_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['user', 'question'], name='content_com_user_id_1b305f_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_com_user_id_58aa6a_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['practice_attempt'], name='content_com_practic_f7ddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['test_attempt'], name='content_com_test_at_16e689_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['is_correct'], name='content_com_is_corr_ad9daf_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestionattempt',
            index=models.Index(fields=['attempted_at'], name='content_com_attempt_84acbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionquestionattempt',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'cycle_number', 'attempt_number'), name='unique_comprehension_question_attempt_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='grammarpracticeattempt',
            index=models.Index(fields=['user', 'focus'], name='content_gra_user_id_ff8b81_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarpracticeattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_gra_user_id_a3015a_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarpracticeattempt',
            index=models.Index(fields=['is_passed'], name='content_gra_is_pass_114fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarpracticeattempt',
            index=models.Index(fields=['attempted_at'], name='content_gra_attempt_efc45d_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarpracticeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_grammar_practice_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['focus'], name='content_gra_focus_i_b82dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['question_type'], name='content_gra_questio_bf6e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['difficulty'], name='content_gra_difficu_23df45_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarrule',
            index=models.Index(fields=['concept'], name='content_gra_concept_317c78_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarrule',
            constraint=models.UniqueConstraint(fields=('concept', 'order'), name='unique_rule_order_per_concept'),
        ),
        migrations.AddIndex(
            model_name='grammarexample',
            index=models.Index(fields=['rule'], name='content_gra_rule_id_7924d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarexample',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='unique_example_order_per_rule'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['user', 'focus'], name='content_gra_user_id_a28b99_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['user', 'focus', 'is_mastered'], name='content_gra_user_id_13f1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_gra_user_id_f28c25_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['created_at'], name='content_gra_created_1e7436_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammartestattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_grammar_test_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='grammarquestionattempt',
            index=models.Index(fields=['user', 'question'], name='content_gra_user_id_e4c204_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestionattempt',
            index=models.Index(fields=['user', 'is_correct'], name='content_gra_user_id_354d28_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestionattempt',
            index=models.Index(fields=['practice_attempt'], name='content_gra_practic_052ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestionattempt',
            index=models.Index(fields=['test_attempt'], name='content_gra_test_at_05aaec_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestionattempt',
            index=models.Index(fields=['attempted_at'], name='content_gra_attempt_e621e1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonchunk',
            index=models.Index(fields=['lesson', 'order'], name='content_les_lesson__bc65f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonchunk',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_chunk_order_per_lesson'),
        ),
        migrations.AddIndex(
            model_name='chunkwritingfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_a113ed_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkwritingfocus',
            index=models.Index(fields=['depth_level'], name='content_chu_depth_l_e2e930_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkwritingfocus',
            index=models.Index(fields=['sequence_order'], name='content_chu_sequenc_7329c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkwritingfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_writing_focus_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_ea6fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['concept'], name='content_chu_concept_268b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['depth_level'], name='content_chu_depth_l_b8685f_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkgrammarfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_grammar_focus_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='chunkcomprehensionfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_728a90_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkcomprehensionfocus',
            index=models.Index(fields=['level'], name='content_chu_level_81ce1c_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkcomprehensionfocus',
            index=models.Index(fields=['depth_level'], name='content_chu_depth_l_5d10cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkcomprehensionfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_comprehension_focus_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='pronunciationfocus',
            index=models.Index(fields=['chunk'], name='content_pro_chunk_i_023772_idx'),
        ),
        migrations.AddConstraint(
            model_name='pronunciationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_pronunciation_focus_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['user', 'focus'], name='content_pro_user_id_aa2039_idx'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_pro_user_id_9cf2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['attempt_type'], name='content_pro_attempt_913dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='pronunciationattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_pronunciation_attempt_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='pronunciationmastery',
            index=models.Index(fields=['user', 'is_mastered'], name='content_pro_user_id_a37d04_idx'),
        ),
        migrations.AddConstraint(
            model_name='pronunciationmastery',
            constraint=models.UniqueConstraint(fields=('user', 'focus'), name='unique_user_pronunciation_mastery'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocus',
            index=models.Index(fields=['chunk', 'depth_level'], name='content_chu_chunk_i_b8f911_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocus',
            index=models.Index(fields=['mark'], name='content_chu_mark_id_d789f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_punctuation_focus_order_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'mark'), name='unique_punc_mark_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='punctuationpracticeattempt',
            index=models.Index(fields=['user', 'focus'], name='content_pun_user_id_d92be7_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationpracticeattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_pun_user_id_e0a046_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationpracticeattempt',
            index=models.Index(fields=['is_passed'], name='content_pun_is_pass_f44e2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='punctuationpracticeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_punctuation_practice_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='punctuationquestion',
            index=models.Index(fields=['focus', 'difficulty'], name='content_pun_focus_i_a0831e_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationquestion',
            index=models.Index(fields=['question_type'], name='content_pun_questio_d709ed_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationrule',
            index=models.Index(fields=['mark'], name='content_pun_mark_id_b79789_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationexample',
            index=models.Index(fields=['rule'], name='content_pun_rule_id_a2701c_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocusrule',
            index=models.Index(fields=['focus', 'order'], name='content_chu_focus_i_aebf3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocusrule',
            constraint=models.UniqueConstraint(fields=('focus', 'rule'), name='unique_rule_per_focus_mapping'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['user', 'focus'], name='content_pun_user_id_1f42cf_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['user', 'focus', 'is_mastered'], name='content_pun_user_id_08d071_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_pun_user_id_d20d6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='punctuationtestattempt',
            constraint=models.UniqueConstraint(fields=('user', 'focus', 'cycle_number', 'attempt_number'), name='unique_punctuation_test_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['textbook', 'number'], name='content_uni_textboo_609731_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('textbook', 'number'), name='unique_unit_number_per_textbook'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit', 'number'], name='content_les_unit_id_8ad3f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'number'), name='unique_lesson_number_per_unit'),
        ),
        migrations.AddIndex(
            model_name='unittestanswer',
            index=models.Index(fields=['question', 'is_correct'], name='content_uni_questio_366314_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestsession',
            index=models.Index(fields=['user', 'unit'], name='content_uni_user_id_3d59a9_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestsession',
            index=models.Index(fields=['user', 'passed'], name='content_uni_user_id_e3ca34_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestsession',
            index=models.Index(fields=['user', 'attempt_number'], name='content_uni_user_id_21c04e_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestsession',
            index=models.Index(fields=['started_at'], name='content_uni_started_cd374a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unittestsession',
            constraint=models.UniqueConstraint(fields=('user', 'unit', 'attempt_number'), name='unique_unit_test_attempt_per_user'),
        ),
        migrations.AddIndex(
            model_name='unitwritingtask',
            index=models.Index(fields=['unit'], name='content_uni_unit_id_93fb56_idx'),
        ),
        migrations.AddIndex(
            model_name='unitwritingtask',
            index=models.Index(fields=['stage'], name='content_uni_stage_73df71_idx'),
        ),
        migrations.AddIndex(
            model_name='unitwritingtask',
            index=models.Index(fields=['difficulty_level'], name='content_uni_difficu_1b3649_idx'),
        ),
        migrations.AddIndex(
            model_name='unitwritingtask',
            index=models.Index(fields=['order'], name='content_uni_order_c549a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitwritingtask',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='unique_task_order_per_unit'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['lesson', 'word'], name='content_voc_lesson__4a6fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['chunk', 'word'], name='content_voc_chunk_i_8e506b_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyattempt',
            index=models.Index(fields=['user', 'vocab_item'], name='content_voc_user_id_6c6daa_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyattempt',
            index=models.Index(fields=['user', 'session_id'], name='content_voc_user_id_df7301_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_voc_user_id_5f089d_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestquestion',
            index=models.Index(fields=['session', 'domain'], name='content_uni_session_3d32d9_idx'),
        ),
        migrations.AddIndex(
            model_name='unittestquestion',
            index=models.Index(fields=['session', 'difficulty'], name='content_uni_session_9c136c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvocabmastery',
            index=models.Index(fields=['user', 'mastery_level'], name='content_stu_user_id_16edac_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentvocabmastery',
            constraint=models.UniqueConstraint(fields=('user', 'vocab_item'), name='unique_user_vocab_mastery'),
        ),
        migrations.AddIndex(
            model_name='vocabularyunittestattempt',
            index=models.Index(fields=['user', 'unit_test_session'], name='content_voc_user_id_bb3408_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyunittestattempt',
            index=models.Index(fields=['user', 'lesson'], name='content_voc_user_id_03a545_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyunittestattempt',
            index=models.Index(fields=['user', 'chunk'], name='content_voc_user_id_a8abc9_idx'),
        ),
        migrations.AddIndex(
            model_name='writingprompt',
            index=models.Index(fields=['focus'], name='content_wri_focus_i_28b09f_idx'),
        ),
        migrations.AddIndex(
            model_name='writingprompt',
            index=models.Index(fields=['task'], name='content_wri_task_id_3113d9_idx'),
        ),
        migrations.AddIndex(
            model_name='writingprompt',
            index=models.Index(fields=['prompt_type'], name='content_wri_prompt__3f6a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpracticeattempt',
            index=models.Index(fields=['user', 'focus'], name='content_wri_user_id_724f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpracticeattempt',
            index=models.Index(fields=['user', 'prompt'], name='content_wri_user_id_5ef0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpracticeattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_wri_user_id_55dca5_idx'),
        ),
        migrations.AddIndex(
            model_name='writingpracticeattempt',
            index=models.Index(fields=['is_passed'], name='content_wri_is_pass_cacb11_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingpracticeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'prompt', 'cycle_number', 'attempt_number'), name='unique_writing_practice_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['user', 'focus'], name='content_wri_user_id_62ff34_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['user', 'task'], name='content_wri_user_id_58ce82_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['user', 'prompt'], name='content_wri_user_id_b82631_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['user', 'cycle_number'], name='content_wri_user_id_fc0265_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['is_mastered'], name='content_wri_is_mast_26b9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='writingtestattempt',
            index=models.Index(fields=['created_at'], name='content_wri_created_f6b113_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingtestattempt',
            constraint=models.UniqueConstraint(fields=('user', 'prompt', 'cycle_number', 'attempt_number'), name='unique_writing_test_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='writingtestattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('focus__isnull', False), ('task__isnull', True)), models.Q(('focus__isnull', True), ('task__isnull', False)), _connector='OR'), name='either_focus_or_task'),
        ),
    ]
