# Generated by Django 5.2.9 on 2026-02-04 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('english_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lesson_audio/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_level', models.CharField(help_text='Example: 9th, 10th, Inter, BA', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.comprehensionquestion')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrammarConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(help_text='e.g. Parts of Speech, Tense, Clause, Sentence Structure', max_length=100)),
                ('order_index', models.PositiveIntegerField(help_text='Controls global progression order across the curriculum')),
            ],
            options={
                'ordering': ['order_index', 'name'],
                'indexes': [models.Index(fields=['slug'], name='content_gra_slug_4bcbfb_idx'), models.Index(fields=['category'], name='content_gra_categor_fd4d73_idx'), models.Index(fields=['order_index'], name='content_gra_order_i_703431_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkGrammarFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('depth_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_instances', to='content.grammarconcept')),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('rewrite', 'Rewrite Sentence'), ('identify', 'Identify Part / Function')], default='mcq', max_length=30)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('explanation', models.TextField(blank=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkgrammarfocus')),
            ],
            options={
                'ordering': ['focus_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrammarAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.grammarquestion')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='content.grammarconcept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.grammarrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkgrammarfocus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_questions', to='content.lesson'),
        ),
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display order within the lesson')),
                ('english_text', models.TextField()),
                ('translated_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chunk_audio/')),
                ('translated_audio_file', models.FileField(blank=True, null=True, upload_to='chunk_audio_urdu/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chunkgrammarfocus',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_focuses', to='content.lessonchunk'),
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('recording', models.FileField(blank=True, null=True, upload_to='student_audio/')),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to='content.lessonchunk')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(help_text='Controls global learning progression')),
            ],
            options={
                'ordering': ['order_index', 'name'],
                'indexes': [models.Index(fields=['symbol'], name='content_pun_symbol_98e243_idx'), models.Index(fields=['order_index'], name='content_pun_order_i_5ec06a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkPunctuationFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(help_text="e.g. 'Comma in Lists', 'Apostrophe for Possession'", max_length=200)),
                ('focus_description', models.TextField()),
                ('depth_level', models.PositiveSmallIntegerField(help_text='1 = Introductory, 5 = Advanced', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sequence_order', models.PositiveSmallIntegerField(help_text='Max 3 punctuation focuses per chunk', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_focuses', to='content.lessonchunk')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_instances', to='content.punctuationmark')),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('insert', 'Insert Correct Punctuation'), ('fix', 'Correct the Sentence'), ('identify', 'Identify Error')], default='mcq', max_length=30)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('explanation', models.TextField(blank=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkpunctuationfocus')),
            ],
            options={
                'ordering': ['focus_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.punctuationquestion')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='PunctuationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='content.punctuationmark')),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.punctuationrule')),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.chunkpunctuationfocus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punctuation_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.textbook')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.unit'),
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('urdu', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('antonyms', models.TextField(blank=True, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default='noun', max_length=20)),
                ('chunk', models.ForeignKey(blank=True, help_text='Optional: link vocabulary to a specific chunk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to='content.lessonchunk')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to='content.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'word'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.vocabularyitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentVocabMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('mastery_level', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Needs Review'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='content.vocabularyitem')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions_data', models.JSONField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_test_attempts', to='content.lessonchunk')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_test_attempts', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('meaning', 'Meaning'), ('synonym', 'Synonym'), ('antonym', 'Antonym'), ('fill_blank', 'Fill in the blank')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.vocabularyitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.vocabularytestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_test_sessions', to='content.lessonchunk')),
            ],
        ),
        migrations.AddField(
            model_name='vocabularytestquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.vocabularytestsession'),
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='content.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('sentence', models.TextField()),
                ('ai_score', models.IntegerField()),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('writing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.writingtask')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GrammarPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='content.chunkgrammarfocus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='content_gra_student_1ecdf6_idx'), models.Index(fields=['focus'], name='content_gra_focus_i_46b9a8_idx'), models.Index(fields=['attempted_at'], name='content_gra_attempt_efc45d_idx')],
                'unique_together': {('student', 'focus')},
            },
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['focus'], name='content_gra_focus_i_b82dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['question_type'], name='content_gra_questio_bf6e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['difficulty'], name='content_gra_difficu_23df45_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['student'], name='content_gra_student_5f95ff_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['question'], name='content_gra_questio_185f61_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['is_correct'], name='content_gra_is_corr_5db677_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['attempted_at'], name='content_gra_attempt_b15f59_idx'),
        ),
        migrations.AddConstraint(
            model_name='grammarattempt',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_attempt_per_question'),
        ),
        migrations.AddConstraint(
            model_name='grammarrule',
            constraint=models.UniqueConstraint(fields=('concept', 'order'), name='unique_rule_order_per_concept'),
        ),
        migrations.AddConstraint(
            model_name='grammarexample',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='unique_example_order_per_rule'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['student'], name='content_gra_student_8e55b2_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['focus'], name='content_gra_focus_i_0f068d_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['created_at'], name='content_gra_created_1e7436_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonchunk',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_chunk_order_per_lesson'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_ea6fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['concept'], name='content_chu_concept_268b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkgrammarfocus',
            index=models.Index(fields=['depth_level'], name='content_chu_depth_l_b8685f_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkgrammarfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_focus_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_47c126_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocus',
            index=models.Index(fields=['mark'], name='content_chu_mark_id_d789f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkpunctuationfocus',
            index=models.Index(fields=['depth_level'], name='content_chu_depth_l_e775d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_punctuation_order_per_chunk'),
        ),
        migrations.AddIndex(
            model_name='punctuationquestion',
            index=models.Index(fields=['focus'], name='content_pun_focus_i_44d9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationquestion',
            index=models.Index(fields=['question_type'], name='content_pun_questio_d709ed_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationquestion',
            index=models.Index(fields=['difficulty'], name='content_pun_difficu_aa365e_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationattempt',
            index=models.Index(fields=['student'], name='content_pun_student_4ec7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationattempt',
            index=models.Index(fields=['question'], name='content_pun_questio_612816_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationattempt',
            index=models.Index(fields=['is_correct'], name='content_pun_is_corr_ce140d_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['student'], name='content_pun_student_cf9c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['focus'], name='content_pun_focus_i_921ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['textbook', 'number'], name='content_uni_textboo_609731_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit', 'number'], name='content_les_unit_id_8ad3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['lesson', 'word'], name='content_voc_lesson__4a6fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['chunk', 'word'], name='content_voc_chunk_i_8e506b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentvocabmastery',
            constraint=models.UniqueConstraint(fields=('student_id', 'vocab_item'), name='unique_student_vocab_mastery'),
        ),
    ]
