# Generated by Django 5.2.9 on 2026-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarquestion',
            name='correct_answer',
            field=models.CharField(help_text='Must exactly match one of the options (for MCQs)', max_length=255),
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='options',
            field=models.TextField(blank=True, help_text='For MCQs: enter one option per line', null=True),
        ),
    ]
