# Generated by Django 5.2.9 on 2026-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyTestAnswer',
        ),
        migrations.DeleteModel(
            name='VocabularyTestAttempt',
        ),
        migrations.DeleteModel(
            name='VocabularyTestQuestion',
        ),
        migrations.DeleteModel(
            name='VocabularyTestSession',
        ),
        migrations.AddField(
            model_name='vocabularyunittestattempt',
            name='answers_data',
            field=models.JSONField(default=list, help_text="Snapshot of student's answers for this attempt"),
        ),
    ]
