# Generated by Django 5.2.9 on 2026-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='questions_snapshot',
            field=models.JSONField(help_text='Stores the state of questions at test time for audit'),
        ),
    ]
