# Generated by Django 5.1.4 on 2025-11-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Present Perfect Tense'", max_length=200)),
                ('explanation', models.TextField(help_text='Explain the grammar rule here.')),
                ('examples', models.TextField(help_text='Add example sentences here.')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_points', to='content.lesson')),
            ],
        ),
    ]
