# Generated by Django 5.1.4 on 2025-11-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_grammarpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the comprehension question here.')),
                ('answer', models.TextField(help_text='Enter the correct answer here.')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_questions', to='content.lesson')),
            ],
        ),
    ]
