# Generated by Django 5.2.9 on 2026-02-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_vocabularytestanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronunciationattempt',
            name='chunk',
        ),
        migrations.AlterField(
            model_name='pronunciationattempt',
            name='focus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.pronunciationfocus'),
            preserve_default=False,
        ),
    ]
