# Generated by Django 5.2.9 on 2026-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_grammarquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarquestion',
            name='options',
            field=models.TextField(blank=True, help_text='For MCQs: Enter one option per line.', null=True),
        ),
    ]
