# Generated by Django 5.2.9 on 2026-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_punctuationtestattempt_questions_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punctuationquestion',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
