# Generated by Django 5.2.9 on 2026-02-09 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_punctuationquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='punctuationtestattempt',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='depth_level',
            field=models.PositiveSmallIntegerField(help_text='1 = Basic, 5 = Advanced', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='focus_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='sequence_order',
            field=models.PositiveSmallIntegerField(help_text='Maximum three teaching steps per chunk', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='questions_snapshot',
            field=models.JSONField(),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'mark'), name='unique_mark_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='punctuationexample',
            constraint=models.UniqueConstraint(fields=('rule', 'sentence'), name='unique_example_per_rule'),
        ),
        migrations.AddConstraint(
            model_name='punctuationquestion',
            constraint=models.UniqueConstraint(fields=('focus', 'question_text'), name='unique_question_per_focus'),
        ),
        migrations.AddConstraint(
            model_name='punctuationrule',
            constraint=models.UniqueConstraint(fields=('mark', 'rule_text'), name='unique_rule_per_mark'),
        ),
    ]
