# Generated by Django 5.1.4 on 2025-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comprehensionquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularyitem',
            old_name='definition',
            new_name='meaning',
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='urdu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='antonyms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='example_sentence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='synonyms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
