# Generated by Django 5.2.9 on 2026-03-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_pronunciationattempt_chunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittestanswer',
            name='student_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('literal', 'Literal'), ('inferential', 'Inferential'), ('evaluative', 'Evaluative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='grammar_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.grammarconcept'),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='punctuation_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.punctuationmark'),
        ),
        migrations.AlterField(
            model_name='unittestquestion',
            name='vocabulary_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.vocabularyitem'),
        ),
        migrations.AlterField(
            model_name='unittestsession',
            name='domain_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='unittestsession',
            name='test_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vocabularyunittestattempt',
            name='answers_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vocabularyunittestattempt',
            name='questions_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vocabularyunittestattempt',
            name='unit_test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_attempts', to='content.unittestsession'),
        ),
    ]
