# Generated by Django 5.2.9 on 2026-02-09 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_punctuationtestattempt_is_mastered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkComprehensionFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
                ('level', models.CharField(choices=[('literal', 'Literal'), ('inferential', 'Inferential'), ('evaluative', 'Evaluative')], default='literal', max_length=20)),
                ('sequence_order', models.PositiveSmallIntegerField(help_text='Order of focus within the chunk (Literal → Inferential → Evaluative)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'ordering': ['chunk_id', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ChunkPunctuationFocusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Teaching order inside the focus (max 3 rules).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'ordering': ['focus_id', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='comprehensionattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.AlterModelOptions(
            name='comprehensionquestion',
            options={'ordering': ['focus_id', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='chunkpunctuationfocus',
            name='content_chu_depth_l_e775d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationattempt',
            name='content_pun_student_4ec7a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationattempt',
            name='content_pun_questio_612816_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationattempt',
            name='content_pun_is_corr_ce140d_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationquestion',
            name='content_pun_focus_i_44d9e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationquestion',
            name='content_pun_questio_d709ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationquestion',
            name='content_pun_difficu_aa365e_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationtestattempt',
            name='content_pun_student_cf9c8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationtestattempt',
            name='content_pun_focus_i_921ef0_idx',
        ),
        migrations.RenameField(
            model_name='comprehensionattempt',
            old_name='timestamp',
            new_name='attempted_at',
        ),
        migrations.RenameField(
            model_name='comprehensionquestion',
            old_name='answer',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='comprehensionattempt',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comprehensionattempt',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='comprehensionquestion',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='comprehensionquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='comprehensionattempt',
            name='open_ended_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehensionattempt',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprehensionattempt',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_attempts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('open_ended', 'Open Ended')], default='mcq', max_length=30),
        ),
        migrations.AlterField(
            model_name='punctuationquestion',
            name='options',
            field=models.TextField(blank=True, help_text='Semicolon-separated', null=True),
        ),
        migrations.AddIndex(
            model_name='comprehensionattempt',
            index=models.Index(fields=['student'], name='content_com_student_865455_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionattempt',
            index=models.Index(fields=['question'], name='content_com_questio_d92997_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionattempt',
            index=models.Index(fields=['is_correct'], name='content_com_is_corr_466e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionattempt',
            index=models.Index(fields=['attempted_at'], name='content_com_attempt_126a4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionattempt',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_comprehension_attempt_per_question'),
        ),
        migrations.AddField(
            model_name='chunkcomprehensionfocus',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_focuses', to='content.lessonchunk'),
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='focus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunkcomprehensionfocus'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['focus'], name='content_com_focus_i_95b6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['question_type'], name='content_com_questio_84f823_idx'),
        ),
        migrations.AddIndex(
            model_name='comprehensionquestion',
            index=models.Index(fields=['difficulty'], name='content_com_difficu_d4ac75_idx'),
        ),
        migrations.AddField(
            model_name='chunkpunctuationfocusrule',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_rules', to='content.chunkpunctuationfocus'),
        ),
        migrations.AddField(
            model_name='chunkpunctuationfocusrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_focuses', to='content.punctuationrule'),
        ),
        migrations.AddField(
            model_name='chunkpunctuationfocus',
            name='rules',
            field=models.ManyToManyField(related_name='teaching_instances', through='content.ChunkPunctuationFocusRule', to='content.punctuationrule'),
        ),
        migrations.AddIndex(
            model_name='chunkcomprehensionfocus',
            index=models.Index(fields=['chunk'], name='content_chu_chunk_i_728a90_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkcomprehensionfocus',
            index=models.Index(fields=['level'], name='content_chu_level_81ce1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chunkcomprehensionfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'sequence_order'), name='unique_comprehension_focus_order_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocusrule',
            constraint=models.UniqueConstraint(fields=('focus', 'rule'), name='unique_rule_per_focus'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocusrule',
            constraint=models.UniqueConstraint(fields=('focus', 'order'), name='unique_rule_order_per_focus'),
        ),
    ]
