# Generated by Django 5.1.4 on 2025-12-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_definition_vocabularyitem_meaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.comprehensionquestion')),
            ],
        ),
    ]
