# Generated by Django 5.2.9 on 2026-02-11 15:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_chunkcomprehensionfocus_chunkpunctuationfocusrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punctuationattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='punctuationattempt',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='chunkpunctuationfocus',
            options={'ordering': ['chunk', 'sequence_order'], 'verbose_name': '3. Chunk Punctuation Focus', 'verbose_name_plural': '3. Chunk Punctuation Focuses'},
        ),
        migrations.AlterModelOptions(
            name='chunkpunctuationfocusrule',
            options={'ordering': ['order'], 'verbose_name': '4. Focus-Rule Mapping'},
        ),
        migrations.AlterModelOptions(
            name='punctuationmark',
            options={'ordering': ['order_index'], 'verbose_name': '1. Global Punctuation Mark'},
        ),
        migrations.AlterModelOptions(
            name='punctuationquestion',
            options={'verbose_name': '5. Punctuation Question'},
        ),
        migrations.AlterModelOptions(
            name='punctuationrule',
            options={'verbose_name': '2. Global Punctuation Rule'},
        ),
        migrations.AlterModelOptions(
            name='punctuationtestattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Test Result'},
        ),
        migrations.RemoveConstraint(
            model_name='chunkpunctuationfocus',
            name='unique_punctuation_order_per_chunk',
        ),
        migrations.RemoveConstraint(
            model_name='chunkpunctuationfocus',
            name='unique_mark_per_chunk',
        ),
        migrations.RemoveConstraint(
            model_name='chunkpunctuationfocusrule',
            name='unique_rule_per_focus',
        ),
        migrations.RemoveConstraint(
            model_name='chunkpunctuationfocusrule',
            name='unique_rule_order_per_focus',
        ),
        migrations.RemoveConstraint(
            model_name='punctuationexample',
            name='unique_example_per_rule',
        ),
        migrations.RemoveConstraint(
            model_name='punctuationquestion',
            name='unique_question_per_focus',
        ),
        migrations.RemoveConstraint(
            model_name='punctuationrule',
            name='unique_rule_per_mark',
        ),
        migrations.RemoveIndex(
            model_name='chunkpunctuationfocus',
            name='content_chu_chunk_i_47c126_idx',
        ),
        migrations.RemoveIndex(
            model_name='chunkpunctuationfocus',
            name='content_chu_mark_id_d789f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='punctuationmark',
            name='content_pun_symbol_98e243_idx',
        ),
        migrations.RemoveField(
            model_name='chunkpunctuationfocus',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='punctuationquestion',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='punctuationtestattempt',
            name='questions_snapshot',
        ),
        migrations.AddField(
            model_name='punctuationmark',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='punctuationtestattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='depth_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Difficulty Level (1: Beginner, 5: Advanced)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='focus_title',
            field=models.CharField(help_text='e.g., Using Commas in a List', max_length=200),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.punctuationmark'),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocus',
            name='sequence_order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Order within the chunk (1, 2, or 3).'),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocusrule',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chunkpunctuationfocusrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.punctuationrule'),
        ),
        migrations.AlterField(
            model_name='punctuationmark',
            name='order_index',
            field=models.PositiveIntegerField(help_text='Global learning sequence. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='punctuationquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown to help the student learn from mistakes.'),
        ),
        migrations.AlterField(
            model_name='punctuationquestion',
            name='options',
            field=models.TextField(blank=True, default='', help_text="For MCQ: Separate options with '|'. Example: Option A | Option B"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punctuationquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('insert', 'Insert Mark'), ('fix', 'Correct Sentence')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chunkpunctuationfocus'),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='is_mastered',
            field=models.BooleanField(default=False, help_text='Set to True only if score is 100%.'),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='score_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocus',
            constraint=models.UniqueConstraint(fields=('chunk', 'mark'), name='unique_punc_mark_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='chunkpunctuationfocusrule',
            constraint=models.UniqueConstraint(fields=('focus', 'rule'), name='unique_rule_per_focus_mapping'),
        ),
        migrations.DeleteModel(
            name='PunctuationAttempt',
        ),
    ]
