# Generated by Django 5.2.9 on 2026-04-04 15:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_writingacademicyear_writingstage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingattempt',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback shown to the student.'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='ai_rubric_scores',
            field=models.JSONField(blank=True, default=dict, help_text='AI scores per rubric criterion.'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='ai_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score from AI evaluation (0–100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(help_text='Attempt number within this phase for this academic year. No hard cap — but cooldown enforced between Produce failures.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='auto_checks',
            field=models.JSONField(blank=True, default=dict, help_text="Results of automatic checks. Format: {'capital_start': True, 'full_stop_end': True, 'min_word_count': True, 'verb_present': True, 'keywords_found': ['word1', 'word2'], 'keywords_missing': ['word3']}"),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='auto_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score from automatic/keyword evaluation (0–100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='cooldown_task',
            field=models.TextField(blank=True, help_text='Directed focus task shown to student during cooldown. Generated on fail and shown immediately on the fail screen.'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='intervention_flags',
            field=models.JSONField(blank=True, default=list, help_text="Sentence-level issues detected. Format: [{'sentence': '...', 'issue': '...', 'fix_exercise': '...'}]"),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='next_attempt_allowed_at',
            field=models.DateTimeField(blank=True, help_text='When the student may attempt Produce again after a failure. Set to 24 hours after a failed Produce attempt.', null=True),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the teacher reviewed this attempt.', null=True),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who reviewed this attempt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text="Teacher's written feedback shown to the student."),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='teacher_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score assigned by teacher (overrides AI score if set).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='writingintervention',
            name='fix_exercise',
            field=models.TextField(help_text="The single targeted exercise shown to the student. Example: 'Rewrite this sentence with a verb: The old man slowly.'"),
        ),
        migrations.AlterField(
            model_name='writingintervention',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='True when the student has attempted the fix exercise. Does not need to be perfect — attempting is enough to proceed.'),
        ),
        migrations.AlterField(
            model_name='writingintervention',
            name='issue_label',
            field=models.CharField(help_text="Plain English description of the problem. Example: 'This sentence has no verb.'", max_length=200),
        ),
        migrations.AlterField(
            model_name='writingintervention',
            name='student_fix',
            field=models.TextField(blank=True, help_text="The student's response to the fix exercise."),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='ai_rubric',
            field=models.JSONField(blank=True, default=dict, help_text="Rubric for AI evaluation. Format: {'criterion': {'max_score': 5, 'description': '...'}}. Used for AI+Teacher evaluated stages only."),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='conversion_note',
            field=models.TextField(help_text="Plain English explanation of what changed and why. Example: 'The relative clause was removed and the subject repeated.'"),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='dissect_question',
            field=models.TextField(help_text="The identification question shown to the student. Example: 'Which part is the subject? Which part is the verb?'"),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='imitate_frame',
            field=models.TextField(help_text='The sentence or paragraph frame for the Imitate phase. Use ___ for blanks. Example: ___ [subject] ___ [verb] ___ [object].'),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='min_word_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override the stage default minimum word count for this unit. Leave blank to use the stage default.', null=True),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='model_sentence_converted',
            field=models.TextField(help_text='Simplified or converted version for comparison. Example: complex sentence broken into simple sentences.'),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='produce_prompt',
            field=models.TextField(help_text='The writing task for the Produce phase. No frame is given. Student writes independently. Should relate to unit content.'),
        ),
        migrations.AlterField(
            model_name='writingstagecontent',
            name='required_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords the student must use. Used for keyword-evaluated stages only.'),
        ),
    ]
