# Generated by Django 5.2.9 on 2026-02-12 12:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_punctuationattempt_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punctuationtestattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Punctuation Test Attempt', 'verbose_name_plural': 'Punctuation Test Attempts'},
        ),
        migrations.RemoveField(
            model_name='punctuationtestattempt',
            name='attempt_number',
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='is_mastered',
            field=models.BooleanField(default=False, help_text='Automatically True when score_percent == 100.'),
        ),
        migrations.AlterField(
            model_name='punctuationtestattempt',
            name='score_percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['student', 'focus'], name='content_pun_student_71f534_idx'),
        ),
        migrations.AddIndex(
            model_name='punctuationtestattempt',
            index=models.Index(fields=['student', 'focus', 'is_mastered'], name='content_pun_student_3c1ffa_idx'),
        ),
    ]
