# Generated by Django 5.1.4 on 2025-12-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_vocabularyattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('grammar_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.grammarpoint')),
            ],
        ),
    ]
