# Generated by Django 5.1.4 on 2025-12-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_grammarattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('english_text', models.TextField(help_text='15–20 sentences of English text')),
                ('urdu_translation', models.TextField(blank=True, help_text='Aligned Urdu translation for the chunk')),
                ('english_audio', models.FileField(blank=True, null=True, upload_to='lesson_audio/english/')),
                ('urdu_audio', models.FileField(blank=True, null=True, upload_to='lesson_audio/urdu/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
