# Generated by Django 5.1.4 on 2025-12-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_lessonchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='english_text',
            field=models.TextField(blank=True, help_text='Optional: full English lesson text'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='translated_text',
            field=models.TextField(blank=True, help_text='Optional: full Urdu/Punjabi/Pashto translation'),
        ),
        migrations.AlterField(
            model_name='sentenceattempt',
            name='writing_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.writingtask'),
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('recording', models.FileField(blank=True, null=True, upload_to='student_audio/')),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback on pronunciation/intonation')),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_attempts', to='content.lessonchunk')),
            ],
        ),
    ]
