# Generated by Django 5.1.4 on 2025-12-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_lesson_english_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonchunk',
            name='english_audio',
        ),
        migrations.RemoveField(
            model_name='lessonchunk',
            name='urdu_audio',
        ),
        migrations.RemoveField(
            model_name='lessonchunk',
            name='urdu_translation',
        ),
        migrations.AddField(
            model_name='lessonchunk',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chunk_audio/'),
        ),
        migrations.AddField(
            model_name='lessonchunk',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='english_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='order',
            field=models.PositiveIntegerField(help_text='Display order within the lesson'),
        ),
    ]
