# Generated by Django 5.1.4 on 2025-12-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_lessonchunk_english_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonchunk',
            name='translated_audio_file',
            field=models.FileField(blank=True, help_text='Urdu audio', null=True, upload_to='chunk_audio_urdu/'),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='audio_file',
            field=models.FileField(blank=True, help_text='English audio', null=True, upload_to='chunk_audio/'),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='translated_text',
            field=models.TextField(blank=True, help_text='Urdu translation of the chunk'),
        ),
    ]
