# Generated by Django 5.1.4 on 2025-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_lessonchunk_translated_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default='noun', max_length=20),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='antonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='urdu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
