# Generated by Django 5.2.9 on 2026-01-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_vocabularyitem_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprehensionattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='grammarattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='pronunciationattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='sentenceattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyitem',
            options={'ordering': ['lesson_id', 'word']},
        ),
        migrations.AlterField(
            model_name='comprehensionattempt',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comprehensionquestion',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comprehensionquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grammarattempt',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grammarpoint',
            name='examples',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grammarpoint',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grammarpoint',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='english_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chunk_audio/'),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='translated_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chunk_audio_urdu/'),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pronunciationattempt',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pronunciationattempt',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sentenceattempt',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabularyattempt',
            name='student_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='prompt',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='lessonchunk',
            unique_together={('lesson', 'order')},
        ),
        migrations.CreateModel(
            name='StudentVocabMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('mastery_level', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Needs Review'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='content.vocabularyitem')),
            ],
            options={
                'unique_together': {('student_id', 'vocab_item')},
            },
        ),
    ]
