# Generated by Django 5.2.9 on 2026-01-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_comprehensionattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonchunk',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentvocabmastery',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='class_level',
            field=models.CharField(help_text='Example: 9th, 10th, Inter, BA', max_length=50),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit', 'number'], name='content_les_unit_id_8ad3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['textbook', 'number'], name='content_uni_textboo_609731_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['lesson', 'word'], name='content_voc_lesson__4a6fc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonchunk',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_chunk_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='studentvocabmastery',
            constraint=models.UniqueConstraint(fields=('student_id', 'vocab_item'), name='unique_student_vocab_mastery'),
        ),
    ]
