# Generated by Django 5.2.9 on 2026-01-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_lessonchunk_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='chunk',
            field=models.ForeignKey(blank=True, help_text='Optional: link vocabulary to a specific chunk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_items', to='content.lessonchunk'),
        ),
        migrations.AddIndex(
            model_name='vocabularyitem',
            index=models.Index(fields=['chunk', 'word'], name='content_voc_chunk_i_8e506b_idx'),
        ),
    ]
