# Generated by Django 5.2.9 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_vocabularytestattempt_vocabularytestquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularytestattempt',
            name='questions_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
