# Generated by Django 5.2.9 on 2026-01-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_vocabularytestattempt_questions_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('rewrite', 'Rewrite')], default='mcq', max_length=50)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['grammar_point_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrammarTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.IntegerField(blank=True, null=True)),
                ('correct_answers', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('questions_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='grammarpoint',
            options={'ordering': ['lesson_id', 'chunk_id', 'title']},
        ),
        migrations.RemoveField(
            model_name='grammarattempt',
            name='grammar_point',
        ),
        migrations.RemoveField(
            model_name='grammarattempt',
            name='student_id',
        ),
        migrations.AddField(
            model_name='grammarattempt',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grammarattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_points', to='content.lessonchunk'),
        ),
        migrations.AddIndex(
            model_name='grammarpoint',
            index=models.Index(fields=['lesson'], name='content_gra_lesson__274463_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarpoint',
            index=models.Index(fields=['chunk'], name='content_gra_chunk_i_1873df_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarpoint',
            index=models.Index(fields=['title'], name='content_gra_title_7ae138_idx'),
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='grammar_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.grammarpoint'),
        ),
        migrations.AddField(
            model_name='grammarattempt',
            name='grammar_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.grammarquestion'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['student'], name='content_gra_student_5f95ff_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['grammar_question'], name='content_gra_grammar_a6abd6_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['timestamp'], name='content_gra_timesta_070e19_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarattempt',
            index=models.Index(fields=['is_correct'], name='content_gra_is_corr_5db677_idx'),
        ),
        migrations.AddField(
            model_name='grammartestattempt',
            name='grammar_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='content.grammarpoint'),
        ),
        migrations.AddField(
            model_name='grammartestattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['grammar_point'], name='content_gra_grammar_56cbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['question_type'], name='content_gra_questio_bf6e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarquestion',
            index=models.Index(fields=['difficulty'], name='content_gra_difficu_23df45_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['student'], name='content_gra_student_8e55b2_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['grammar_point'], name='content_gra_grammar_3cc529_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['created_at'], name='content_gra_created_1e7436_idx'),
        ),
        migrations.AddIndex(
            model_name='grammartestattempt',
            index=models.Index(fields=['score_percent'], name='content_gra_score_p_68dd79_idx'),
        ),
    ]
